on:
  push:
    branches:
      - demangan

name: ðŸš€ Deploy website on push (Demangan)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install #use yarn

      - name: Clean Config
        run: npx quasar clean --qconf

      - name: Build PWA
        run: npx quasar build -m pwa

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/pwa
          clean: true
          branch: gh-demangan
